---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: centos-7.2
  - name: centos-6.6
  - name: debian-8.6
  - name: fedora-24

suites:
  - name: default
    run_list:
      - recipe[change1::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
