---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[change1::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      nginx:
        conf:
          listen_port: '39999'
        page:
          header: 'This is MY_TEST_HEADER2 here!'
  - name: installing_nginx
    run_list:
      - recipe[change1::install_nginx]
    verifier:
      inspec_tests:
        - test/smoke/install_nginx
    attributes:
